### ISSUE TITLE
Role name in test.yml not found

### ISSUE THREAD

**Issue by bolek2000** [nginxinc/ansible-role-nginx-oss#2]
Thank you for proving this playbook, but the --syntax-test revealed:
ERROR! the role 'ansible-role-nginx-oss' was not found.

I changed it to  'nginxinc.nginx-oss' and it worked.

Also with my ansible 2.4 installation I had the following warnings, maybe someting for future releases:

[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a
 future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by alessfg** [comment]
Hi @bolek2000, using `--syntax-test` in a playbook with `ansible-role-nginx-oss` will fail if you installed the playbook from Ansible Galaxy. Syntax test works in the travis script because travis is testing this repo, not the Ansible Galaxy install. If you want to test `--syntax-test` with the Ansible Galaxy installation, then as you mentioned you have to change `ansible-role-nginx-oss` to `nginxinc.nginx-oss`. 

Re your second comment, this is a known issue. However, `import_tasks` and `include_tasks` where only introduced in Ansible 2.4, and as such would be a breaking change if I were to implement them at this stage.

Did this address your issues?

**Comment by bolek2000** [comment]
Hi Allessandro,

I'm fine with the answers, I found my workaround. Just wanted to report back, what I discovered. I'm not familiar with Travis so I guess the normal use case would be to download with ansible-galaxy and then try to run the playbook like you decribed in your README, which gives the same error I stated with the --syntax-check.

**Comment by alessfg** [comment]
Cool. I updated the README since the previous sample playbook would indeed report an error. For that matter it would not work at all if the role was installed via Ansible Galaxy. Marking this issue as resolved.
